### ISSUE TITLE
ARM-8 - wat?

### ISSUE THREAD

**Issue by rodjek** [puppetlabs/puppet-rfc#54]
As stated in the spec

> Why should this work be done? What are its benefits? Who's asking for it? How does it compare to the competition, if any?

I'd really like to see some answers to these questions.  This spec seems like a extremely complex solution to a problem that doesn't exist.

> a user may wish long for the perceived "simpler times"

Yeah...

**Comment by ahpook** [comment]
Closing, as this did not get implemented, largely due to the exact concerns raised here by @rodjek and @wfarr
